spring:
  datasource:
    url: jdbc:tc:postgresql:16:///einvoice_test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    clean-disabled: false
    clean-on-validation-error: true

logging:
  level:
    com.einvoice: DEBUG
