package com.einvoice.core.service;

import com.einvoice.core.domain.AuthorityConfig;
import com.einvoice.core.domain.Invoice;
import com.einvoice.core.domain.enums.ArtifactType;
import com.einvoice.core.domain.enums.Authority;
import java.util.List;

/**
 * Interface for authority-specific submission engines.
 *
 * <p>Implementations must be safe for concurrent use (no mutable instance state).</p>
 */
public interface AuthorityEngine {

    Authority getSupportedAuthority();

    /**
     * Generates the authority-specific payload for an invoice.
     *
     * @param invoice the invoice
     * @param config the authority configuration
     * @return the generated payload string
     */
    String generatePayload(Invoice invoice, AuthorityConfig config);

    /**
     * Submits a payload to the authority.
     *
     * @param invoice the originating invoice (needed for post-submission artifacts)
     * @param payload the payload generated by {@link #generatePayload}
     * @param config the authority configuration
     * @return the submission result including any generated artifacts
     */
    SubmissionResultDto submit(Invoice invoice, String payload,
                               AuthorityConfig config);

    ArtifactType getPayloadArtifactType();

    ArtifactType getResponseArtifactType();

    ArtifactType getClearedArtifactType();

    /**
     * Computes the invoice hash used for hash-chain management.
     *
     * @param payload the unsigned payload
     * @return the hash, or null if hashing is not supported
     */
    default String computeInvoiceHash(String payload) {
        return null;
    }

    List<ArtifactType> getExpectedArtifactTypes();
}
